##
## Entitas Generated Components for shmupwarz
##
## do not edit this file
##
import bosco/ECS
import bosco/Sprite


type
  Component* = enum
    Bounds
    Bullet
    ColorAnimation
    Destroy
    Enemy
    Expires
    Firing
    Health
    Layer
    Life
    Mine
    Mouse
    Player
    Position
    Resource
    ScaleAnimation
    Scale
    Score
    SoundEffect
    Velocity



  BoundsComponent* = ref object of IComponent
    radius* : float64

  BulletComponent* = ref object of IComponent
    bullet* : bool

  ColorAnimationComponent* = ref object of IComponent
    redMin* : float64
    redMax* : float64
    redSpeed* : float64
    greenMin* : float64
    greenMax* : float64
    greenSpeed* : float64
    blueMin* : float64
    blueMax* : float64
    blueSpeed* : float64
    alphaMin* : float64
    alphaMax* : float64
    alphaSpeed* : float64
    redAnimate* : bool
    greenAnimate* : bool
    blueAnimate* : bool
    alphaAnimate* : bool
    repeat* : bool

  DestroyComponent* = ref object of IComponent
    destroy* : bool

  EnemyComponent* = ref object of IComponent
    enemy* : bool

  ExpiresComponent* = ref object of IComponent
    delay* : float64

  FiringComponent* = ref object of IComponent
    firing* : bool

  HealthComponent* = ref object of IComponent
    health* : float64
    maximumHealth* : float64

  LayerComponent* = ref object of IComponent
    ordinal* : int

  LifeComponent* = ref object of IComponent
    count* : int

  MineComponent* = ref object of IComponent
    mine* : bool

  MouseComponent* = ref object of IComponent
    x* : float64
    y* : float64

  PlayerComponent* = ref object of IComponent
    player* : bool

  PositionComponent* = ref object of IComponent
    x* : float64
    y* : float64

  ResourceComponent* = ref object of IComponent
    path* : string
    sprite* : Sprite

  ScaleAnimationComponent* = ref object of IComponent
    min* : float64
    max* : float64
    speed* : float64
    repeat* : bool
    active* : bool

  ScaleComponent* = ref object of IComponent
    x* : float64
    y* : float64

  ScoreComponent* = ref object of IComponent
    value* : float64

  SoundEffectComponent* = ref object of IComponent
    effect* : int

  VelocityComponent* = ref object of IComponent
    x* : float64
    y* : float64



